version: '3'

services:
  db:
    image: mamuri-db
    restart: always
    container_name: mamuri-db
    ports:
      - '13060:3306'
    env_file:
      - "./database/mysql_init/.env"
    volumes:
      - "/usr/mysql/data:/var/lib/mysql"

  server:
    image: mamuri-server
    restart: always
    container_name: mamuri-server
    ports:
      - '8080:8080'

  daangn_api:
    image: daangn-api-server
    restart: always
    container_name: daangn-api-server
    ports:
      - '18080:8080'

  joongna_api:
    image: joongna-api-server
    restart: always
    container_name: joongna-api-server
    ports:
      - '18081:8080'

  bunjang_api:
    image: bunjang-api-server
    restart: always
    container_name: bunjang-api-server
    ports:
      - '18082:8080'

  ngrok:
    image: mamuri-ngrok
    container_name: mamuri-ngrok
    env_file:
      - "ngrok/ngrok.yml"
    ports:
      - '4040:4040'