version: '3'

services:
  db:
    image: mamuri-db
    restart: always
    container_name: mamuri-db-container
    ports:
      - '13060:3306'
    env_file:
      - "./database/mysql_init/.env"
    volumes:
      - "/usr/mysql/data:/var/lib/mysql"

  daangn_api:
    image: daangn-api-server
    restart: always
    container_name: daangn-api-server-container
    ports:
      - '18080:8080'

  joongna_api:
    image: joongna-api-server
    restart: always
    container_name: joongna-api-server-container
    ports:
      - '18081:8080'

  bunjang_api:
    image: bunjang-api-server
    restart: always
    container_name: bunjang-api-server-container
    ports:
      - '18082:8080'